In [1]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import StratifiedKFold
from sklearn.tree import DecisionTreeClassifier
from imblearn.over_sampling import SMOTE
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import numpy as np

In [2]:
data = load_breast_cancer()
X = data.data
y = data.target

In [3]:
clf = DecisionTreeClassifier()
smote = SMOTE()

In [4]:
skf = StratifiedKFold(n_splits=5)

In [5]:
accuracies = []

In [6]:
for train_index, test_index in skf.split(X, y):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

    # Aplicar SMOTE solo al conjunto de entrenamiento
    X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

    # Entrenar el modelo
    clf.fit(X_train_resampled, y_train_resampled)

    # Realizar predicciones
    y_pred = clf.predict(X_test)

    # Calcular métricas
    acc = accuracy_score(y_test, y_pred)
    accuracies.append(acc)

    # Mostrar la matriz de confusión
    print("Matriz de Confusión:")
    print(confusion_matrix(y_test, y_pred))

    # Mostrar el reporte de clasificación
    print("Reporte de Clasificación:")
    print(classification_report(y_test, y_pred))

Matriz de Confusión:
[[40  3]
 [ 7 64]]
Reporte de Clasificación:
              precision    recall  f1-score   support

           0       0.85      0.93      0.89        43
           1       0.96      0.90      0.93        71

    accuracy                           0.91       114
   macro avg       0.90      0.92      0.91       114
weighted avg       0.92      0.91      0.91       114

Matriz de Confusión:
[[37  6]
 [ 3 68]]
Reporte de Clasificación:
              precision    recall  f1-score   support

           0       0.93      0.86      0.89        43
           1       0.92      0.96      0.94        71

    accuracy                           0.92       114
   macro avg       0.92      0.91      0.91       114
weighted avg       0.92      0.92      0.92       114

Matriz de Confusión:
[[39  3]
 [ 3 69]]
Reporte de Clasificación:
              precision    recall  f1-score   support

           0       0.93      0.93      0.93        42
           1       0.96      0.96      